DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

blog/urls.py
from django.urls import path,include
from django.conf.urls import url
from . import views

app_name='blog'
urlpatterns=[
        path('',views.IndexView.as_view(),name='index'),
        path('blog/',views.IndexView.as_view(),name='blog'),
        path('about/',views.about,name='about'),
        path('contact/',views.contact,name='contact'),
	path('contact/thanks/',views.thanks,name='thanks'),
        url(r'^post/(?P<pk>[0-9]+)/$',views.PostDetailView.as_view(),name='detail'),
        url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.ArchivesView.as_view(),name='archives'),
        url(r'^category/(?P<pk>[0-9]+)/$',views.CategoryView.as_view(),name='category'),
        url(r'^tag/(?P<pk>[0-9]+)/$',views.TagView.as_view(),name='tag'),
        path('search/',views.search,name='search'),
        ]

comments/urls.py
from django.conf.urls import url

from . import views

app_name='comments'
urlpatterns=[
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$',views.post_comment,name='post_comment'),
    ]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include

from blog.feeds import AllPostsRssFeed
from DjangoUeditor import urls as djud_urls
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('',include('comments.urls')),
    path('all/rss/',AllPostsRssFeed(),name='rss'),
    path('ueditor/',include(djud_urls)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from DjangoUeditor.models import UEditorField

class Category(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    title=models.CharField(max_length=70)

    body=UEditorField(height=300,width=1000,default=u'',blank=True,imagePath="uploads/blog/images/",
                           toolbars='besttome',filePath='uploads/blog/files/')

    created_time=models.DateTimeField()
    modified_time=models.DateTimeField()

    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    tags=models.ManyToManyField(Tag,blank=True)

    author=models.ForeignKey(User,on_delete=models.CASCADE)

    views=models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk':self.pk})

    class Meta:
        ordering=['-created_time']

    def increase_views(self):
        self.views+=1
        self.save(update_fields=['views'])

comments/models.py
from django.db import models

class Comment(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField(max_length=255)
    url=models.URLField(blank=True)
    text=models.TextField()
    created_time=models.DateTimeField(auto_now_add=True)

    post=models.ForeignKey('blog.Post',on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]

blog/forms.py
from django import forms

class ContactForm(forms.Form):
	name=forms.CharField()
	email=forms.EmailField()
	subject=forms.CharField(max_length=100)
	message=forms.CharField(widget=forms.Textarea)

blog/views.py
from django.shortcuts import render,get_object_or_404

from .forms import ContactForm
from django.core.mail import send_mail,get_connection
from django.http import Http404, HttpResponse, HttpResponseRedirect
from .models import Post,Category,Tag
from comments.forms import CommentForm
from django.views.generic import ListView,DetailView
from django.db.models import Q

class IndexView(ListView):
        model=Post
        template_name='blog/index.html'
        context_object_name='post_list'
        paginate_by=10

        def get_context_data(self,**kwargs):
                context=super().get_context_data(**kwargs)
                paginator=context.get('paginator')
                page=context.get('page_obj')
                is_paginated=context.get('is_paginated')

                pagination_data=self.pagination_data(paginator,page,is_paginated)

                context.update(pagination_data)
                return context

        def pagination_data(self,paginator,page,is_paginated):
                if not is_paginated:
                        return {}
                left=[]
                right=[]

                left_has_more=False

                right_has_more=False

                first=False
                last=False

                page_number=page.number

                total_pages=paginator.num_pages

                page_range=paginator.page_range

                if page_number==1:
                    right=page_range[page_number:page_number+2]

                    if right[-1]<total_pages-1:
                        right_has_more=True

                    if right[-1]< total_pages:
                        last=True

                elif page_number==total_pages:
                    left=page_range[(page_number-3)if(page_number-3)>0 else 0:page_number-1]
                    if left[0]>2:
                        left_has_more=True

                    if left[0]>1:
                        first=True
                else:
                    left=page_range[(page_number-3) if (page_number-3) >0 else 0:page_number-1]
                    right=page_range[page_number:page_number+2]

                    if right[-1]<total_pages-1:
                        right_has_more=True

                    if right[-1]<total_pages:
                        last=True

                    if left[0]>2:
                        left_has_more=True

                    if left[0]>1:
                        first=True

                data={
                        'left':left,
                        'right':right,
                        'left_has_more':left_has_more,
                        'right_has_more':right_has_more,
                        'first':first,
                        'last':last,
                        }

                return data

def blog(request):
        return render(request,'blog/blog.html')

def about(request):
        return render(request,'blog/about.html')
	
def contact(request):
	if request.method=='POST':
		form=ContactForm(request.POST)
		if form.is_valid():
			cd=form.cleaned_data
			send_mail(
				cd.get('email','632226765@qq.com')+cd['subject'],
				cd['message'],
				'632226765@qq.com',
				['632226765@qq.com'],
				fail_silently=False
				)
			return HttpResponseRedirect('/contact/thanks/')
	else:
		form=ContactForm()
	return render(request,'blog/contact.html',{'form':form})

def thanks(request):
	return render(request,'blog/thanks.html')

def search(request):
        q=request.GET.get('q')
        error_msg=''

        if not q:
                error_msg="请输入关键词"
                return render(request,'blog/index.html',{'error_msg':error_msg})
        post_list=Post.objects.filter(Q(title__icontains=q)|Q(body__icontains=q))
        return render(request,'blog/index.html',{'error_msg':error_msg,
                                                 'post_list':post_list
                                                 })

class TagView(ListView):
        model=Post
        template_name='blog/index.html'
        context_object_name='post_list'

        def get_queryset(self):
                tag=get_object_or_404(Tag,pk=self.kwargs.get('pk'))
                return super(TagView,self).get_queryset().filter(tags=tag)


class PostDetailView(DetailView):
        model=Post
        template_name='blog/detail.html'
        context_object_name='post'

        def get(self,request,*args,**kwargs):
                response=super(PostDetailView,self).get(request,*args,**kwargs)
                self.object.increase_views()
                return response

        def get_object(self,queryset=None):
                post=super(PostDetailView,self).get_object(queryset=None)
                return post

        def get_context_data(self,**kwargs):
                context=super(PostDetailView,self).get_context_data(**kwargs)
                form=CommentForm()
                comment_list=self.object.comment_set.all()
                context.update({
                        'form':form,
                        'comment_list':comment_list
                        })
                return context

class ArchivesView(ListView):
        model=Post
        template_name='blog/index.html'
        context_object_name='post_list'

        def get_queryset(self):
                return super(ArchivesView,self).get_queryset().filter(created_time__year=self.kwargs.get('year'),created_time__month=self.kwargs.get('month'))



class CategoryView(ListView):
        model=Post
        template_name='blog/index.html'
        context_object_name='post_list'

        def get_queryset(self):
                cate=get_object_or_404(Category,pk=self.kwargs.get('pk'))
                return super(CategoryView,self).get_queryset().filter(category=cate)

templates/blog/about.html
{% extends 'base.html' %}

{% block main %}
<div class="blog-post-body">
							<h2><a href="">About Author</a></h2>
							<div class="blog-post-text">

								<p>一名大学生</p>
							</div>
</div>
{% endblock main %}

templates/blog/blog.html
{% extends 'base.html' %}

{% block main %}

{% endblock main %}

templates/blog/contact.html
{% extends 'base.html' %}

{% block main %}

<div class="blog-post-body">
	<h1>Contact us</h1>
	{% if form.errors %}
		<p style="color:red;">
			Please correct the error{{ form.errors|pluralize }} below.
			all forms all required!
		</p>
	{% endif %}

<form action="" method="post" novalidate>
{% csrf_token %}
<table>
	<div class="post-meta">name：
	{{ form.name }}
	email:
	{{ form.email }}
	</div>
	<div class="post-meta">subject:
	{{ form.subject }}
	</div>
	<div class="post-meta">message:<br />
	{{ form.message }}
	
</table>
<input type="submit" value="Submit">
</form>
</div>

{% endblock main %}

templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}

<div class="blog-post-body">
							<h2>{{ post.title }}</h2>
							<div class="post-meta">
							<span>by <a href="#">{{ post.author }}</a></span>
							/<span><a href="#">{{ post.category.name }}</a></span>
							/<span><i class="fa fa-clock-o"></i>{{ post.created_time }}</span>
							/<span>{{ post.views }}阅读</span>
							/<span><i class="fa fa-comment-o"></i>{{ post.comment_set.count }}</span>
							</div>
							<p>{{ post.body|safe }}</p>
</div>
<hr />
<div><h3>标签：</h3>
{% for tag in post.tags.all %}
<ul>
	<li><a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a></li>
</ul>
{% endfor %}
</div>
<section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
		    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
		    {% csrf_token %}
                    <div class="row">
                    <div class="col-md-4">
				    <label for="{{ form.name.id_for_label }}">名字：</label>
				    {{ form.name }}
				    {{ form.name.errors }}
			        </div>
                    <div class="col-md-4">
				    <label for="{{ form.email.id_for_label }}">邮箱：</label>
				    {{ form.email }}
				    {{ form.email.errors }}
                    </div>
                    <div class="col-md-4">
				    <label for="{{ form.url.id_for_label }}">网址：</label>
				    {{ form.url }}
				    {{ form.url.errors }}  
					</div>
                    <div class="col-md-12" >
				    <label for="{{ form.text.id_for_label }}">评论：</label><br />
				    {{ form.text }}
				    {{ form.text.errors }}
					<br />
				    <button type="submit" class="comment-btn"><i class="fa fa-send"></i></button>
                    </div>
                    </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
			    <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
				{% for comment in comment_list %}
                            <li class="comment-item">
				    <h4><span class="nickname">{{ comment.name }}</span>&nbsp;&nbsp;
				    <time class="submit-date"> {{ comment.created_time }}</time>&nbsp;&nbsp;
					<span class="email">{{ comment.email }}</span></h4>
                            <div class="text">&nbsp;&nbsp;&nbsp;&nbsp;
							{{ comment.text }}
							<hr />
							</div>
                            </li>
			     {% empty %}
			     没有评论了
			     {% endfor %}
                        </ul>
                    </div>
                </section>
{% endblock main %}

templates/blog/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load blog_tags %}

{% block push %}
<section class="main-slider">
			<ul class="bxslider">
				{% get_first_post as first_post %}
				<li><div class="slider-item"><img src="{% static 'blog/images/1140x500-2.jpg' %}" title="Funky roots" /><h2><a href="{{ first_post.get_absolute_url }}" title="post-1">{{ first_post }}</a></h2></div></li>
				{% get_second_post as second_post %}
				<li><div class="slider-item"><img src="{% static 'blog/images/1140x500-1.jpg' %}" title="Funky roots" /><h2><a href="{{ second_post.get_absolute_url }}" title="post-2">{{ second_post }}</a></h2></div></li>
				{% get_third_post as third_post %}
				<li><div class="slider-item"><img src="{% static 'blog/images/1140x500-3.jpg' %}" title="Funky roots" /><h2><a href="{{ third_post.get_absolute_url }}" title="post-3">{{ third_post }}</a></h2></div></li>
			</ul>
</section>
{% endblock push %}

{% block main %}
	{% if error_msg %}
		<p>{{ error_msg }}</p>
	{% endif %}

<div class="blog-post-body">
{% for post in post_list %}
							<h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
							<div class="post-meta"><span>by <a href="#">{{ post.author }}</a></span>/<span><i class="fa fa-clock-o"></i>{{ post.created_time }}</span>/<span>{{ post.category.name }}</span>/<span>{{ post.views }}阅读</span>/<span><i class="fa fa-comment-o"></i> <a href="{{ post.get_absolute_url }}">{{ post.comment_set.count }}</a></span></div>
							<p>{{ post.body|truncatechars_html:100 |safe }}</p>
							<div class="read-more"><a href="{{ post.get_absolute_url }}">Continue Reading</a></div>
{% empty %}
<div class="no-post">暂时还没有文章</div>
{% endfor %}
<div class="pagination">
      <!-- 简单分页效果 -->
	    {% if is_paginated %}
                <div class="pagination-simple">
			{% if first %}
			<a href="?page=1">1</a>
			{% endif %}
			{% if left %}
				{% if left_has_more %}
				<span>...</span>
				{% endif %}
				{% for i in left %}
					<a href="?page={{ i }}">{{ i }}</a>
				{% endfor %}
			{% endif %}
			<a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
			{% if right %}
				{% for i in right %}
				<a href="?page={{ i }}">{{ i }}</a>
				{% endfor %}
				{% if right_has_more %}
				<span>...</span>
				{% endif %}
			{% endif %}
			{% if last %}
			<a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
			{% endif %}
		</div>
		{% endif %}
    </div>
</div>


{% endblock main %}

templates/blog/post.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<meta name="description" content="">
		<meta name="author" content="">
		<link rel="icon" href="favicon.ico">
		<title>Renda - clean blog theme based on Bootstrap</title>
		<!-- Bootstrap core CSS -->
		<link href="css/bootstrap.min.css" rel="stylesheet">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
		<!-- Custom styles for this template -->
		<link href="css/jquery.bxslider.css" rel="stylesheet">
		<link href="css/style.css" rel="stylesheet">
	</head>
	<body>
		<!-- Navigation -->
		<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
				</div>
				<div id="navbar" class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li class="active"><a href="index.html">Home</a></li>
						<li><a href="#about">Lifestyle</a></li>
						<li><a href="#contact">Travel</a></li>
						<li><a href="#contact">Fashion</a></li>
						<li><a href="about.html">About Me</a></li>
						<li><a href="about.html">Contact</a></li>
					</ul>

					<ul class="nav navbar-nav navbar-right">
						<li><a href="#"><i class="fa fa-facebook"></i></a></li>
						<li><a href="#"><i class="fa fa-twitter"></i></a></li>
						<li><a href="#"><i class="fa fa-instagram"></i></a></li>
						<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
						<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
						<li><a href="#"><i class="fa fa-reddit"></i></a></li>
					</ul>

				</div>
				<!--/.nav-collapse -->
			</div>
		</nav>

		<div class="container">
		<header>
			<a href="index.html"><img src="images/logo.png"></a>
		</header>
		<section>
			<div class="row">
				<div class="col-md-8">
					<article class="blog-post">
						<div class="blog-post-image">
							<a href="post.html"><img src="images/750x500-5.jpg" alt=""></a>
						</div>
						<div class="blog-post-body">
							<h2><a href="post.html">Vintage-Inspired Finds for Your Home</a></h2>
							<div class="post-meta"><span>by <a href="#">Jamie Mooze</a></span>/<span><i class="fa fa-clock-o"></i>March 14, 2015</span>/<span><i class="fa fa-comment-o"></i> <a href="#">343</a></span></div>
							<div class="blog-post-text">

								<p>A newly-developed mathematical method can detect geometric structure in neural activity in the brain. “Previously, in order to understand this structure, scientists needed to relate neural activity to some specific external stimulus,” said Vladimir Itskov, associate professor of mathematics at Penn State University. “Our method is the first to be able to reveal this structure without our knowing an external stimulus ahead of time. We’ve now shown that our new method will allow us to explore the organizational structure of neurons without knowing their function in advance.”</p>

								<p>“The traditional methods used by researchers to analyze the relationship between the activities of neurons were adopted from physics,” said Carina Curto, associate professor of mathematics at Penn State, “but neuroscience data doesn’t necessarily play by the same rules as data from physics, so we need new tools. Our method is a first step toward developing a new mathematical toolkit to uncover the structure of neural circuits with unknown function in the brain.”</p>

								<h3>Math reveals structure in neural activity in the brain</h3>
								<p>The method — clique topology — was developed by an interdisciplinary team of researchers at Penn State, the University of Pennsylvania, the Howard Hughes Medical Institute, and the University of Nebraska-Lincoln. The method is described in a paper that will be posted in the early online edition of the journal Proceedings of the National Academy of Sciences during the week ending October 23, 2015.</p>

								<p>“We have adopted approaches from the field of algebraic topology that previously had been used primarily in the domain of pure mathematics and have applied them to experimental data on the activity of place cells — specialized neurons in the part of the brain called the hippocampus that sense the position of an animal in its environment,” said Curto.</p>
							</div>
						</div>
					</article>
				</div>
				<div class="col-md-4 sidebar-gutter">
					<aside>
					<!-- sidebar-widget -->
					<div class="sidebar-widget">
						<h3 class="sidebar-title">About Me</h3>
						<div class="widget-container widget-about">
							<a href="post.html"><img src="images/author.jpg" alt=""></a>
							<h4>Jamie Mooz</h4>
							<div class="author-title">Designer</div>
							<p>While everyone’s eyes are glued to the runway, it’s hard to ignore that there are major fashion moments on the front row too.</p>
						</div>
					</div>
					<!-- sidebar-widget -->
					<div class="sidebar-widget">
						<h3 class="sidebar-title">Featured Posts</h3>
						<div class="widget-container">
							<article class="widget-post">
								<div class="post-image">
									<a href="post.html"><img src="images/90x60-1.jpg" alt=""></a>
								</div>
								<div class="post-body">
									<h2><a href="post.html">The State of the Word 2014</a></h2>
									<div class="post-meta">
										<span><i class="fa fa-clock-o"></i> 2. august 2015</span> <span><a href="post.html"><i class="fa fa-comment-o"></i> 23</a></span>
									</div>
								</div>
							</article>
							<article class="widget-post">
								<div class="post-image">
									<a href="post.html"><img src="images/90x60-2.jpg" alt=""></a>
								</div>
								<div class="post-body">
									<h2><a href="post.html">Why The Muppets Needs to Channel 30 Rock</a></h2>
									<div class="post-meta">
										<span><i class="fa fa-clock-o"></i> 2. august 2015</span> <span><a href="post.html"><i class="fa fa-comment-o"></i> 23</a></span>
									</div>
								</div>
							</article>
							<article class="widget-post">
								<div class="post-image">
									<a href="post.html"><img src="images/90x60-3.jpg" alt=""></a>
								</div>
								<div class="post-body">
									<h2><a href="post.html">The State of the Word 2014</a></h2>
									<div class="post-meta">
										<span><i class="fa fa-clock-o"></i> 2. august 2015</span> <span><a href="post.html"><i class="fa fa-comment-o"></i> 23</a></span>
									</div>
								</div>
							</article>
							<article class="widget-post">
								<div class="post-image">
									<a href="post.html"><img src="images/90x60-4.jpg" alt=""></a>
								</div>
								<div class="post-body">
									<h2><a href="post.html">Vintage-Inspired Finds for Your Home</a></h2>
									<div class="post-meta">
										<span><i class="fa fa-clock-o"></i> 2. august 2015</span> <span><a href="post.html"><i class="fa fa-comment-o"></i> 23</a></span>
									</div>
								</div>
							</article>
							<article class="widget-post">
								<div class="post-image">
									<a href="post.html"><img src="images/90x60-5.jpg" alt=""></a>
								</div>
								<div class="post-body">
									<h2><a href="post.html">The State of the Word 2014</a></h2>
									<div class="post-meta">
										<span><i class="fa fa-clock-o"></i> 2. august 2015</span> <span><a href="post.html"><i class="fa fa-comment-o"></i> 23</a></span>
									</div>
								</div>
							</article>
						</div>
					</div>
					<!-- sidebar-widget -->
					<div class="sidebar-widget">
						<h3 class="sidebar-title">Socials</h3>
						<div class="widget-container">
							<div class="widget-socials">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-instagram"></i></a>
								<a href="#"><i class="fa fa-google-plus"></i></a>
								<a href="#"><i class="fa fa-dribbble"></i></a>
								<a href="#"><i class="fa fa-reddit"></i></a>
							</div>
						</div>
					</div>
					<!-- sidebar-widget -->
					<div class="sidebar-widget">
						<h3 class="sidebar-title">Categories</h3>
						<div class="widget-container">
							<ul>
								<li><a href="#">Fashion</a></li>
								<li><a href="#">Art</a></li>
								<li><a href="#">Design</a></li>
								<li><a href="#">Featured</a></li>
								<li><a href="#">Graphics</a></li>
								<li><a href="#">Peoples</a></li>
								<li><a href="#">Uncategorized</a></li>
							</ul>
						</div>
					</div>
					</div>
					</aside>
				</div>
			</div>
		</section>
		</div><!-- /.container -->

		<footer class="footer">

			<div class="footer-socials">
				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-instagram"></i></a>
				<a href="#"><i class="fa fa-google-plus"></i></a>
				<a href="#"><i class="fa fa-dribbble"></i></a>
				<a href="#"><i class="fa fa-reddit"></i></a>
			</div>

			<div class="footer-bottom">
				<i class="fa fa-copyright"></i> Copyright 2015. All rights reserved.<br>
				More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a>
			</div>
		</footer>

		<!-- Bootstrap core JavaScript
			================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="js/jquery.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<script src="js/jquery.bxslider.js"></script>
		<script src="js/mooz.scripts.min.js"></script>
	</body>
</html>

templates/blog/thanks.html
{% extends 'base.html' %}

{% block main %}

<div class="blog-post-body">
<h1>Thanks for you attention!</h1>
</div>

{% endblock main %}